version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}