version: '3.9'

services:
  streetmap:
    build: .
    ports: 
      - "8000:8000"
    environment:
      - PG_DB=${PG_DB}
      - PG_USER=${PG_USER}
      - PG_HOST=${PG_HOST}
      - PG_PASSWORD=${PG_PASSWORD}

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DB}